#!/bin/bash

# This script verifies that the assembler works correctly.
# The cmp files are generated by running the provided assembler
# on the asm files. The assembler is then verified by comparing
# the .cmp files with the .hack files generated by our assembler.

ASSEMBLERPATH=".."
JAVACOMMAND="java -cp $ASSEMBLERPATH/MyAssembler/bin com/nandtotetris/myassembler/MyAssembler"

function assembleAndVerify {

    ASMFILEPATH="$ASSEMBLERPATH/$1/$1$2.asm"
    $JAVACOMMAND $ASMFILEPATH
    HACKFILEPATH="$ASSEMBLERPATH/$1/$1$2.hack" 
    CMPFILEPATH="$ASSEMBLERPATH/$1/$1$2.cmp"

    DIFF=$(diff $HACKFILEPATH $CMPFILEPATH) 
    if [ "$DIFF" == "" ] 
     then
     echo "$1$2 output verified"
    fi
}

assembleAndVerify add
assembleAndVerify max
assembleAndVerify max L
assembleAndVerify pong
assembleAndVerify pong L
assembleAndVerify rect
assembleAndVerify rect L
